import Head from "next/head";
import { ReactNode } from "react";
import styles from "../styles/components/Layout.module.scss";
import Logo from "../public/logo.svg";
import Link from "next/link";
import Button from "./Button";
import { SiDiscord, SiGithub } from "react-icons/si";
import clsx from "clsx";
import { motion } from "framer-motion";

const menus = {
    소개: "/about",
    프로젝트: "/project",
};

const variants = {
    hidden: { opacity: 0, y: 50 },
    enter: { opacity: 1, y: 0 },
    exit: { opacity: 0, y: -50 },
};

interface Props {
    page?: string;
    className?: string;
    children?: ReactNode;
}

export default function Layout({ page, className, children }: Props) {
    const title = (page ? `${page} - ` : "") + "InfiniteTeam";
    return (
        <div className={styles.container}>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header className={styles.header}>
                <Link href="/">
                    <a>
                        <div className={styles.brand}>
                            <Logo className={styles.logo} />
                            인피니트팀
                        </div>
                    </a>
                </Link>

                <div className={styles.menus}>
                    {Object.entries(menus).map(([name, href]) => (
                        <Link href={href}>
                            <a>
                                <Button link={page !== name}>{name}</Button>
                            </a>
                        </Link>
                    ))}
                </div>
            </header>
            <motion.main
                className={clsx(styles.main, className)}
                variants={variants}
                initial="hidden"
                animate="enter"
                exit="exit"
                transition={{ type: "linear" }}
            >
                {children}
            </motion.main>
            <footer className={styles.footer}>
                <div className={styles.legal}>
                    <span className={styles.copyright}>
                        © 2022 InfiniteTeam. All Rights Reserved.
                    </span>
                    <div className={styles.policy}>
                        <Link href="/tos">
                            <a>이용약관</a>
                        </Link>
                        <Link href="/privacy">
                            <a>개인정보 처리방침</a>
                        </Link>
                    </div>
                </div>
                <div className={styles.social}>
                    <a href="https://discord.gg/7aFczQk">
                        <SiDiscord></SiDiscord>
                    </a>
                    <a href="https://github.com/InfiniteTeam">
                        <SiGithub></SiGithub>
                    </a>
                </div>
            </footer>
        </div>
    );
}
