import Head from "next/head";
import { ReactNode } from "react";
import styles from "../styles/components/Layout.module.scss";
import Logo from "../public/logo.svg";
import Link from "next/link";
import Button from "./Button";

interface Props {
    page?: string;
    children?: ReactNode;
}

export default function Layout({ page, children }: Props) {
    const title = (page ? `${page} - ` : "") + "InfiniteTeam";
    return (
        <div className={styles.container}>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header className={styles.header}>
                <div className={styles.brand}>
                    <Logo className={styles.logo} />
                    인피니트팀
                </div>
                <div className={styles.menus}>
                    <Link href="/">
                        <a>
                            <Button>홈</Button>
                        </a>
                    </Link>
                    <Link href="/about">
                        <a>
                            <Button link>소개</Button>
                        </a>
                    </Link>
                    <Link href="/project">
                        <a>
                            <Button link>프로젝트</Button>
                        </a>
                    </Link>
                </div>
            </header>
            <main className={styles.main}>{children}</main>
            <footer className={styles.footer}>Footer</footer>
        </div>
    );
}
